
package com.mfu.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Address")
public class Address {

	private String entId;
	
	@DynamoDBRangeKey(attributeName = "EntId")
		@DynamoDBAutoGeneratedKey
	public String getEntId() {
		return entId;
	}
	public void setEntId(String entId) {
		this.entId = entId;
	}
		
	// Generated code for attribute: houseNo
	private String houseNo;
	@DynamoDBAttribute(attributeName = "HouseNo")
	public String getHouseNo() {
		return houseNo;
	}
	public void setHouseNo(String param) {
		this.houseNo = param;
	}
		
	// Generated code for attribute: street
	private String street;
	@DynamoDBAttribute(attributeName = "Street")
	public String getStreet() {
		return street;
	}
	public void setStreet(String param) {
		this.street = param;
	}
		
	// Generated code for attribute: province
	private String province;
	@DynamoDBAttribute(attributeName = "Province")
	public String getProvince() {
		return province;
	}
	public void setProvince(String param) {
		this.province = param;
	}
		
	// Generated code for attribute: employee
	private String employeeEntId;
	@DynamoDBHashKey(attributeName = "EmployeeEntId")
	public String getEmployeeEntId() {
		return employeeEntId;
	}
	public void setEmployeeEntId(String param) {
		this.employeeEntId = param;
	}
	    
}
	