
package com.mfu.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Employee")
public class Employee {

	private String entId;
	
	@DynamoDBHashKey(attributeName = "EntId")
		@DynamoDBAutoGeneratedKey
	public String getEntId() {
		return entId;
	}
	public void setEntId(String entId) {
		this.entId = entId;
	}
		
	// Generated code for attribute: firstname
	private String firstname;
	@DynamoDBAttribute(attributeName = "Firstname")
	public String getFirstname() {
		return firstname;
	}
	public void setFirstname(String param) {
		this.firstname = param;
	}
		
	// Generated code for attribute: lastname
	private String lastname;
	@DynamoDBAttribute(attributeName = "Lastname")
	public String getLastname() {
		return lastname;
	}
	public void setLastname(String param) {
		this.lastname = param;
	}
		
	// Generated code for attribute: birthday
	private Date birthday;
	@DynamoDBAttribute(attributeName = "Birthday")
	public Date getBirthday() {
		return birthday;
	}
	public void setBirthday(Date param) {
		this.birthday = param;
	}
		
	// Generated code for attribute: photo
	private String photo;
	@DynamoDBAttribute(attributeName = "Photo")
	public String getPhoto() {
		return photo;
	}
	public void setPhoto(String param) {
		this.photo = param;
	}
		
	private Object photoData;
	public Object getPhotoData() {
		return photoData;
	}
	public void setPhotoData(Object param) {
		this.photoData = param;
	}
		
	// Generated code for attribute: salary
	private int salary;
	@DynamoDBAttribute(attributeName = "Salary")
	public int getSalary() {
		return salary;
	}
	public void setSalary(int param) {
		this.salary = param;
	}
		
	// Generated code for attribute: position
	private String position;
	@DynamoDBAttribute(attributeName = "Position")
	public String getPosition() {
		return position;
	}
	public void setPosition(String param) {
		this.position = param;
	}
		
	// Generated code for attribute: address
	// Generated code for attribute: phone
}
	