
package com.mfu.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Phone")
public class Phone {

	private String entId;
	
	@DynamoDBRangeKey(attributeName = "EntId")
		@DynamoDBAutoGeneratedKey
	public String getEntId() {
		return entId;
	}
	public void setEntId(String entId) {
		this.entId = entId;
	}
		
	// Generated code for attribute: label
	private String label;
	@DynamoDBAttribute(attributeName = "Label")
	public String getLabel() {
		return label;
	}
	public void setLabel(String param) {
		this.label = param;
	}
		
	// Generated code for attribute: number
	private String number;
	@DynamoDBAttribute(attributeName = "Number")
	public String getNumber() {
		return number;
	}
	public void setNumber(String param) {
		this.number = param;
	}
		
	// Generated code for attribute: employee
	private String employeeEntId;
	@DynamoDBHashKey(attributeName = "EmployeeEntId")
	public String getEmployeeEntId() {
		return employeeEntId;
	}
	public void setEmployeeEntId(String param) {
		this.employeeEntId = param;
	}
	    
}
	