
package com.mfu.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "SaleOrder")
public class SaleOrder {

	private String entId;
	
	@DynamoDBRangeKey(attributeName = "EntId")
		@DynamoDBAutoGeneratedKey
	public String getEntId() {
		return entId;
	}
	public void setEntId(String entId) {
		this.entId = entId;
	}
		
	// Generated code for attribute: description
	private String description;
	@DynamoDBAttribute(attributeName = "Description")
	public String getDescription() {
		return description;
	}
	public void setDescription(String param) {
		this.description = param;
	}
		
	// Generated code for attribute: amount
	private int amount;
	@DynamoDBAttribute(attributeName = "Amount")
	public int getAmount() {
		return amount;
	}
	public void setAmount(int param) {
		this.amount = param;
	}
		
	// Generated code for attribute: orderDate
	private Date orderDate;
	@DynamoDBAttribute(attributeName = "OrderDate")
	public Date getOrderDate() {
		return orderDate;
	}
	public void setOrderDate(Date param) {
		this.orderDate = param;
	}
		
	// Generated code for attribute: price
	private double price;
	@DynamoDBAttribute(attributeName = "Price")
	public double getPrice() {
		return price;
	}
	public void setPrice(double param) {
		this.price = param;
	}
		
	// Generated code for attribute: customer
	private String customerEntId;
	@DynamoDBHashKey(attributeName = "CustomerEntId")
	public String getCustomerEntId() {
		return customerEntId;
	}
	public void setCustomerEntId(String param) {
		this.customerEntId = param;
	}
	    
}
	